routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});
Route::group(['middleware' => 'auth'], function() {
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::resource('clientes', 'ClientesController');
    Route::resource('empleados', 'EmpleadosController');
    Route::resource('producto-categorias', 'ProductoCategoriasController');
    Route::resource('productos', 'ProductosController');
    Route::resource('usuarios', 'UsuariosController');
    Route::resource('manos', 'ManosController');
    Route::resource('pies', 'PiesController');
    Route::resource('colores', 'ColoresController');
    Route::resource('CrearCita', 'CitasController');
    Route::resource('keratinas', 'KeratinasController');
    Route::resource('maquillajes', 'MaquillajesController');
    Route::resource('peinados', 'PeinadosController');
    Route::resource('cortes', 'CortesController');
    Route::resource('depilaciones', 'DepilacionesController');
    Route::get('events', 'EventsController@index');
    Route::get('opciones', function () {
        return view('admin.Agenda.agendar');     

    });
    Route::get('servicios', function () {
        return view('admin.servicio.Servicios');
      

    });
});
    /*Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
        Route::resource('login', 'LoginController');
              
    
        });*/
        
   
});



Route::get('/home', 'HomeController@index')->name('home');



Route::get('/home', 'HomeController@index')->name('home');



Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'Auth', 'namespace' => 'Auth'], function () {

   
Route::get('password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.reset');
Route::post('password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}','ForgotPasswordController@showResetForm')->name('password.reset.token');
Route::post('password/reset','ResetPasswordController@reset');
});
Auth::routes();

app/Models/Cliente.php
<?php

namespace multiventas\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cliente extends Model
{
    use SoftDeletes;
    

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    
    protected $primaryKey = 'documento';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'documento',
         'nombre',
         'apellido',
         'direccion',
         'telefono',
         'email',
               
     ];
    /**
     * obtener los productos de los clientes.
     */
    public function products()
    {
        return $this->hasMany('multiventas\Models\Producto','cliente_documento','documento');
    }
}

app/Http/Controllers/Admin/ClientesController.php
<?php

namespace multiventas\Http\Controllers\Admin;

use multiventas\Models\Cliente;
use Illuminate\Http\Request;
use multiventas\Http\Controllers\Controller;

class ClientesController extends Controller
{
    /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $cliente = Cliente::all();
    $params = [
        'title' => 'Lista clientes',
        'cliente' => $cliente,
    ];
    return view('admin.clientes.clientes_list')->with($params);
  }

  /**
   * muestra el formualrio donde se creara el nuevo recurso.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
      $params = [
          'title' => 'Crear Clientes',
      ];
      return view('admin.clientes.clientes_create')->with($params);
  }

  /**
   * almacena un nuevo recurso en la bd.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {

      
      $this->validate($request, [  //es el nombre que viene desde la vista
          'documento'=> 'required|unique:clientes|numeric',
          'nombre' => 'required|alpha',
          'apellido' => 'required|alpha',
          'direccion' => 'required',
          'telefono' => 'required|numeric',
          'email' => 'required|email',
          
      ]);
      $cliente = Cliente::create([    //llama al metodo create del modelo                     
          'documento' => $request->input('documento'),
          'nombre' => $request->input('nombre'),
          'apellido' => $request->input('apellido'),
          'direccion' => $request->input('direccion'),
          'telefono' => $request->input('telefono'),
          'email' => $request->input('email'),
        
      ]);
      return redirect()->route('clientes.index')->with('success', "El cliente <strong>$cliente->nombre</strong> ha sido creada correctamente.");
  }

  /**
   * muestra el recurso especifico para eliminar.
   *
   * @param  int  $documento
   * @return \Illuminate\Http\Response
   */
  public function show($documento)
  {
      try{
          $cliente = Cliente::findOrFail($documento);
          $params = [
              'title' => 'Borrar cliente',
              'Empleado' => $cliente,
          ];
          return view('admin.clientes.clientes_delete',['Clientes' => $cliente]);
         
      }
      catch (ModelNotFoundException $ex) 
      {
          if ($ex instanceof ModelNotFoundException)
          {
              return response()->view('errors.'.'404');
          }
      }
  }

  /**
   *muestro el formulario desde donde se va a editar.
   *
   * @param  int  $documento
   * @return \Illuminate\Http\Response
   */
  public function edit($documento)
  {
      try
      {
          $cliente = Cliente::findOrFail($documento);
          $params = [
              'title' => 'Editar cliente',
              'cliente' => $cliente,
          ];
          return view('admin.clientes.clientes_edit')->with($params);
      }
      catch (ModelNotFoundException $ex) 
      {
          if ($ex instanceof ModelNotFoundException)
          {
              return response()->view('errors.'.'404');
          }
      }
  
  }

  /**
   * almacena las actualizaciones en la bd.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $documento)
  {
      try
      {
          $this->validate($request, [
              'documento',
              'nombre' => 'required|alpha',
              'apellido' => 'required|alpha',
              'direccion' => 'required',
              'telefono' => 'required|numeric',
              'email' => 'required|email',
              
            
          ]);
          $cliente = Cliente::findOrFail($documento);
          $cliente->nombre = $request->input('nombre');
          $cliente->apellido = $request->input('apellido');
          $cliente->direccion = $request->input('direccion');
          $cliente->telefono = $request->input('telefono');
          $cliente->email = $request->input('email');
          $cliente->save();
          return redirect()->route('clientes.index')->with('success', "El cliente <strong>$cliente->nombre</strong> ha sido actualizada.");
      }
      catch (ModelNotFoundException $ex) 
      {
          if ($ex instanceof ModelNotFoundException)
          {
              return response()->view('errors.'.'404');
          }
      }
  }

  /**
   * permite eliminar un registro de la bd.
   *
   * @param  int  $documento
   * @return \Illuminate\Http\Response
   */
  public function destroy($documento)
  {
      try
      {
        $cliente = cliente::findOrFail($documento);
        $cliente->delete();
          return redirect()->route('$cliente.index')->with('success', "El cliente <strong>$$cliente->nombre</strong> ha sido eliminado.");
      }
      catch (ModelNotFoundException $ex) 
      {
          if ($ex instanceof ModelNotFoundException)
          {
              return response()->view('errors.'.'404');
          }
      }
  }
  
}

resources/views/admin/clientes/clientes_create.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h1> <font color="white"><dt> Crear cliente </dt></font></h1>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <form method="post" action="{{ route('clientes.store') }}" data-parsley-validate class="form-horizontal form-label-left">
                      
                        <div class="form-group{{ $errors->has('documento') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="documento"><dt>Documento<span class="required">*</span></dt>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('documento') ?: '' }}" id="documento" name="documento" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('documento'))
                                <span class="help-block">{{ $errors->first('documento') }}</span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre">Nombre <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('nombre') ?: '' }}" id="nombre" name="nombre" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('apellido') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="apellido">Apellido <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('apellido') ?: '' }}" id="apellido" name="apellido" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('apellido'))
                                <span class="help-block">{{ $errors->first('apellido') }}</span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('direccion') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="direccion">Direccion<span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('direccion') ?: '' }}" id="direccion" name="direccion" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('direccion'))
                                <span class="help-block">{{ $errors->first('direccion') }}</span>
                                @endif
                            </div>
                        </div>
                       
                        <div class="form-group{{ $errors->has('telefono') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telefono">Telefono <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('telefono') ?: '' }}" id="telefono" name="telefono" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('telefono'))
                                <span class="help-block">{{ $errors->first('telefono') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email<span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('email') ?: '' }}" id="email" name="email" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('email'))
                                <span class="help-block">{{ $errors->first('email') }}</span>
                                @endif
                            </div>
                        </div>

                         <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <button type="submit" class="btn btn-success">Crear Cliente</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/clientes/clientes_delete.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                <h2> <font color="white"><dt> Confirmar borrar el cliente:  <strong>{{$Clientes->nombre}}</strong> <strong>{{$Clientes->apellido}}</strong></dt></font></h2>
                <div class="clearfix"></div>
                </div>
                <div class="x_content">
                        <h3> <font color="black"><dt> Esta usted seguro que desea eliminar a:  <strong>{{$Clientes->nombre}}</strong> <strong>{{$Clientes->apellido}}</strong></dt></font></h3>
                        <form method="POST" action="{{ route('clientes.destroy', ['documento' => $Clientes->documento]) }}">
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">Si quiero eliminar al cliente </button>
                    </form>
                  </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/clientes/clientes_edit.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2> <font color="white"><dt> Editar Cliente:  <strong>{{$cliente->nombre}}</strong> <strong>{{$cliente->apellido}}</strong></dt></font></h2>
                   <div class="clearfix"></div>
                </div>
                <div class="x_content">
                              <br />                 
                                </div>   <form method="post" action="{{ route('clientes.update', ['documento' => $cliente->documento]) }}" data-parsley-validate class="form-horizontal form-label-left">
                            <div class="form-group{{ $errors->has('documento') ? ' has-error' : '' }}">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="documento">Documento <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" value="{{$cliente->documento}}" id="documento" name="documento" class="form-control col-md-7 col-xs-12" readonly="readonly">
                                        @if ($errors->has('documento'))
                                        <span class="help-block">{{ $errors->first('documento') }}</span>
                                        @endif
                                    </div>
                                </div>
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre">Nombre <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{$cliente->nombre}}" id="nombre" name="nombre" class="form-control col-md-7 col-xs-12" >
                                @if ($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group{{ $errors->has('apellido') ? ' has-error' : '' }}">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="apellido">Apellido<span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" value="{{$cliente->apellido}}" id="apellido" name="apellido" class="form-control col-md-7 col-xs-12">
                                    @if ($errors->has('apellido'))
                                    <span class="help-block">{{ $errors->first('apellido') }}</span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('direccion') ? ' has-error' : '' }}">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="direccion">Direccion <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" value="{{$cliente->direccion}}" id="apellido" name="direccion" class="form-control col-md-7 col-xs-12">
                                        @if ($errors->has('direccion'))
                                        <span class="help-block">{{ $errors->first('direccion') }}</span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('telefono') ? ' has-error' : '' }}">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telefono">Telefono <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" value="{{$cliente->telefono}}" id="telefono" name="telefono" class="form-control col-md-7 col-xs-12">
                                            @if ($errors->has('telefono'))
                                            <span class="help-block">{{ $errors->first('telefono') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email <span class="required">*</span>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" value="{{$cliente->email}}" id="email" name="email" class="form-control col-md-7 col-xs-12">
                                                @if ($errors->has('email'))
                                                <span class="help-block">{{ $errors->first('email') }}</span>
                                                @endif
                                            </div>
                                        </div>

                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <input name="_method" type="hidden" value="PUT">
                                <button type="submit" class="btn btn-success">Guardar Cambios</button>
                                </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/clientes/clientes_list.blade.php
@extends('layout')

@section('content')
<div class="">

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><font color="white">Lista de clientes <a href="{{route('clientes.create')}}" class="btn btn-primary btn"><i class="fa fa-plus"></i> Nuevo </a></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Documento</th>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>Direccion</th>
                                <th>Telefono</th>
                                <th>Email</th>                                
                                <th>Accion</th>
                            </tr>
                        </thead>
                           <tbody>
                            @if (count($cliente))
                            @foreach($cliente as $row)
                            <tr>
                                <td>{{$row->documento}}</td>
                                <td>{{$row->nombre}}</td>
                                <td>{{$row->apellido}}</td>
                                <td>{{$row->direccion}}</td>
                                <td>{{$row->telefono}}</td>
                                <td>{{$row->email}}</td>
                                <td>
                                        <a href="{{ route('clientes.edit', ['id' => $row->documento]) }}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> Editar </a></i> </a>
                                        <a href="{{ route('clientes.show', ['id' => $row->documento]) }}" class="btn btn-danger btn-xs"><i class="fa fa-chevron-left"></i> Eliminar </a></i> </a>
                                        <a href="{{ route('clientes.show', ['id' => $row->documento]) }}" class="btn btn-danger btn-xs"><i class="fa fa-chevron-left"></i> Promocion </a></i> </a>

                                        </td
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop