routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});
Route::group(['middleware' => 'auth'], function() {
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::resource('clientes', 'ClientesController');
    Route::resource('empleados', 'EmpleadosController');
    Route::resource('producto-categorias', 'ProductoCategoriasController');
    Route::resource('productos', 'ProductosController');
    Route::resource('usuarios', 'UsuariosController');
    Route::resource('manos', 'ManosController');
    Route::resource('pies', 'PiesController');
    Route::resource('colores', 'ColoresController');
    Route::resource('CrearCita', 'CitasController');
    Route::resource('keratinas', 'KeratinasController');
    Route::resource('maquillajes', 'MaquillajesController');
    Route::resource('peinados', 'PeinadosController');
    Route::resource('cortes', 'CortesController');
    Route::resource('depilaciones', 'DepilacionesController');
    Route::get('events', 'EventsController@index');
    Route::get('opciones', function () {
        return view('admin.Agenda.agendar');     

    });
    Route::get('servicios', function () {
        return view('admin.servicio.Servicios');
      

    });
});
    /*Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
        Route::resource('login', 'LoginController');
              
    
        });*/
        
   
});



Route::get('/home', 'HomeController@index')->name('home');



Route::get('/home', 'HomeController@index')->name('home');



Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'Auth', 'namespace' => 'Auth'], function () {

   
Route::get('password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.reset');
Route::post('password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}','ForgotPasswordController@showResetForm')->name('password.reset.token');
Route::post('password/reset','ResetPasswordController@reset');
});
Auth::routes();

app/Models/Empleado.php
<?php

namespace multiventas\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Empleado extends Model
{
    use SoftDeletes;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */

    protected $primaryKey = 'documento';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
       'documento',
        'nombre',
        'apellido',
        'direccion',
        'telefono',
        'email',
        'usuario',
        'contrasena',
       
    ];

    /**
     * obtener los productos de la marca.
     */
    public function products()
    {
        return $this->hasMany('multiventas\Models\Producto','empleado_documento','documento');
    }
}

app/Http/Controllers/Admin/EmpleadosController.php
<?php

namespace multiventas\Http\Controllers\Admin;

use multiventas\Models\Empleado;
use multiventas\Models\user;
use Illuminate\Http\Request;
use multiventas\Http\Controllers\Controller;

class EmpleadosController extends Controller
{
      /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $empleados = Empleado::all();
        $params = [
            'title' => 'Lista empleados',
            'empleado' => $empleados,
        ];
        return view('admin.empleados.empleados_list')->with($params);
    }

    /**
     * muestra el formualrio donde se creara el nuevo recurso.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $params = [
            'title' => 'Crear Empleados',
        ];
        return view('admin.empleados.empleados_create')->with($params);
    }

    /**
     * almacena un nuevo recurso en la bd.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        
        $this->validate($request, [  //es el nombre que viene desde la vista
            'documento'=> 'required|unique:empleados|numeric',
            'nombre' => 'required|alpha',
            'apellido' => 'required|alpha',
            'direccion' => 'required',
            'telefono' => 'required|numeric',
            'email' => 'required|email',
            'contrasena' => 'required',
        ]);
        $empleado = empleado::create([    //llama al metodo create del modelo                     
            'documento' => $request->input('documento'),
            'nombre' => $request->input('nombre'),
            'apellido' => $request->input('apellido'),
            'direccion' => $request->input('direccion'),
            'telefono' => $request->input('telefono'),
            'email' => $request->input('email'),
            'contrasena' => $request->input('contrasena'),
        ]);
        $usuario = user::create([
                'name' =>  $request->input(trim('nombre')),
                'email' =>  $request->input(trim('email')),
                'password' => bcrypt( $request->input('contrasena')),
        ]);
        return redirect()->route('empleados.index')->with('success', "El empleado <strong>$empleado->nombre</strong> ha sido creada correctamente.");
    }

    /**
     * muestra el recurso especifico para eliminar.
     *
     * @param  int  $documento
     * @return \Illuminate\Http\Response
     */
    public function show($documento)
    {
        try{
            $empleado = Empleado::findOrFail($documento);
            $params = [
                'title' => 'Borrar empleado',
                'Empleado' => $empleado,
            ];
            return view('admin.empleados.empleados_delete',['empleados' => $empleado]);
           
        }
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }

    /**
     *muestro el formulario desde donde se va a editar.
     *
     * @param  int  $documento
     * @return \Illuminate\Http\Response
     */
    public function edit($documento)
    {
        try
        {
            $empleado = Empleado::findOrFail($documento);
            $params = [
                'title' => 'Editar empleado',
                'empleado' => $empleado,
            ];
            return view('admin.empleados.empleados_edit')->with($params);
        }
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    
    }

    /**
     * almacena las actualizaciones en la bd.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $documento)
    {
        try
        {
            $this->validate($request, [
                'documento'=> 'required|numeric',
                'nombre' => 'required|alpha',
                'apellido' => 'required|alpha',
                'direccion' => 'required',
                'telefono' => 'required|numeric',
                'email' => 'required|email',
                'contrasena' => 'required',
              
            ]);
            $empleado = Empleado::findOrFail($documento);
            $empleado->nombre = $request->input('nombre');
            $empleado->apellido = $request->input('apellido');
            $empleado->direccion = $request->input('direccion');
            $empleado->telefono = $request->input('telefono');
            $empleado->email = $request->input('email');
            $empleado->contrasena = $request->input('contrasena');
            $empleado->save();
        
            return redirect()->route('empleados.index')->with('success', "El empleado <strong>$empleado->nombre</strong> ha sido actualizada.");
        }
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }

    /**
     * permite eliminar un registro de la bd.
     *
     * @param  int  $documento
     * @return \Illuminate\Http\Response
     */
    public function destroy($documento)
    {
        try
        {
            $empleado = Empleado::findOrFail($documento);
            $empleado->delete();
            return redirect()->route('empleados.index')->with('success', "El empleado <strong>$empleado->nombre</strong> ha sido eliminado.");
        }
        catch (ModelNotFoundException $ex) 
        {
            if ($ex instanceof ModelNotFoundException)
            {
                return response()->view('errors.'.'404');
            }
        }
    }
    
}

resources/views/admin/empleados/empleados_create.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2> <font color="white">Crear empleado </h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <form  method="post" action="{{ route('empleados.store') }}" data-parsley-validate class="form-horizontal form-label-left" >
                      
                        <div class="form-group{{ $errors->has('documento') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="documento"><p><font color="black">Documento <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('documento') ?: '' }}" id="documento" name="documento" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('documento'))
                                <span class="help-block">{{ $errors->first('documento') }}</span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre"><p>Nombre <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('nombre') ?: '' }}" id="nombre" name="nombre" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('apellido') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="apellido"><p>Apellido <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('apellido') ?: '' }}" id="apellido" name="apellido" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('apellido'))
                                <span class="help-block">{{ $errors->first('apellido') }}</span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('direccion') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="direccion"><p>Direccion <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('direccion') ?: '' }}" id="direccion" name="direccion" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('apellido'))
                                <span class="help-block">{{ $errors->first('direccion') }}</span>
                                @endif
                            </div>
                        </div>
                       
                        <div class="form-group{{ $errors->has('telefono') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telefono"><p>Telefono <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('telefono') ?: '' }}" id="telefono" name="telefono" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('telefono'))
                                <span class="help-block">{{ $errors->first('telefono') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email"><p>Email <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('email') ?: '' }}" id="email" name="email" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('email'))
                                <span class="help-block">{{ $errors->first('email') }}</span>
                                @endif
                            </div>
                        </div>
                        
                        <div class="form-group{{ $errors->has('contrasena') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="contrasena"><p>Contraseña <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('contrasena') ?: '' }}" id="contrasena" name="contrasena" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('contrasena'))
                                <span class="help-block">{{ $errors->first('contrasena') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <button type="submit" class="btn btn-success">Crear Empleado</button>
                                </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/empleados/empleados_delete.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                        <h2 > <font color="white">Confirmar borrado del empleado</font> </h2>
                      <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <h3>Esta usted seguro que desea eliminar a:  <strong>{{$empleados->nombre}}</strong> <strong>{{$empleados->apellido}}</strong>
                    </h3>

                    <form method="POST" action="{{ route('empleados.destroy', ['documento' => $empleados->documento]) }}">
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">Si quiero eliminar el empleado  </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/empleados/empleados_edit.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2><font color="white"> Empleado</font></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <form method="post" action="{{ route('empleados.update', ['documento' => $empleado->documento]) }}" data-parsley-validate class="form-horizontal form-label-left">
                            <div class="form-group{{ $errors->has('documento') ? ' has-error' : '' }}">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="documento"><p>Documento <span class="required">*</p></span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" value="{{$empleado->documento}}" id="documento" name="documento"  readonly="readonly" class="form-control col-md-7 col-xs-12">
                                        @if ($errors->has('documento'))
                                        <span class="help-block">{{ $errors->first('documento') }}</span>
                                        @endif
                                    </div>
                                </div>
        
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre"><p>Nombre <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{$empleado->nombre}}" id="nombre" name="nombre" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group{{ $errors->has('apellido') ? ' has-error' : '' }}">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="apellido"><p>Apellido <span class="required">*</p></span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" value="{{$empleado->apellido}}" id="apellido" name="apellido" class="form-control col-md-7 col-xs-12">
                                    @if ($errors->has('apellido'))
                                    <span class="help-block">{{ $errors->first('apellido') }}</span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('direccion') ? ' has-error' : '' }}">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="direccion"><p>Direccion <span class="required">*</p></span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" value="{{$empleado->direccion}}" id="apellido" name="direccion" class="form-control col-md-7 col-xs-12">
                                        @if ($errors->has('direccion'))
                                        <span class="help-block">{{ $errors->first('direccion') }}</span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('telefono') ? ' has-error' : '' }}">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telefono"><p>Telefono <span class="required">*</p></span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" value="{{$empleado->telefono}}" id="telefono" name="telefono" class="form-control col-md-7 col-xs-12">
                                            @if ($errors->has('telefono'))
                                            <span class="help-block">{{ $errors->first('telefono') }}</span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email"><p>Email <span class="required">*</p></span>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" value="{{$empleado->email}}" id="email" name="email" class="form-control col-md-7 col-xs-12">
                                                @if ($errors->has('email'))
                                                <span class="help-block">{{ $errors->first('email') }}</span>
                                                @endif
                                            </div>
                                        </div>

                                                                                    <div class="form-group{{ $errors->has('contrasena') ? ' has-error' : '' }}">
                                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="contrasena"><p>Contraseña <span class="required">*</p></span>
                                                    </label>
                                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                                        <input type="text" value="{{$empleado->contrasena}}" id="contrasena" name="contrasena" class="form-control col-md-7 col-xs-12">
                                                        @if ($errors->has('contrasena'))
                                                        <span class="help-block">{{ $errors->first('contrasena') }}</span>
                                                        @endif
                                                    </div>
                                                </div>

                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <input name="_method" type="hidden" value="PUT">
                                <button type="submit" class="btn btn-success">Guardar Cambios</button>
                               </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/empleados/empleados_list.blade.php
@extends('layout')

@section('content'  )
<div class="" >

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2><font color="white">Lista de empleados <a href="{{route('empleados.create')}}" class="btn btn-primary btn"><i class="fa fa-plus"></i>Nuevo </a></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content text-center " >
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Documento</th>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>Direccion</th>
                                <th>Telefono</th>
                                <th>Email</th>                                
                                <th>Contraseña</th>
                                <th>Acción</th>
                            
                            </tr>
                        </thead>
                           <tbody>
                            @if (count($empleado))
                            @foreach($empleado as $row)
                            <tr>
                                <td>{{$row->documento}}</td>
                                <td>{{$row->nombre}}</td>
                                <td>{{$row->apellido}}</td>
                                <td>{{$row->direccion}}</td>
                                <td>{{$row->telefono}}</td>
                                <td>{{$row->email}}</td>
                                <td>{{$row->contrasena}}</td>
                                <td>
                                   <a href="{{ route('empleados.edit', ['id' => $row->documento]) }}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> Editar </a></i> </a>
                                   <a href="{{ route('empleados.show', ['id' => $row->documento]) }}" class="btn btn-danger btn-xs"><i class="fa fa-chevron-left"></i> Eliminar </a></i> </a>
                               </td
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop