routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});
Route::group(['middleware' => 'auth'], function() {
Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::resource('clientes', 'ClientesController');
    Route::resource('empleados', 'EmpleadosController');
    Route::resource('producto-categorias', 'ProductoCategoriasController');
    Route::resource('productos', 'ProductosController');
    Route::resource('usuarios', 'UsuariosController');
    Route::resource('manos', 'ManosController');
    Route::resource('pies', 'PiesController');
    Route::resource('colores', 'ColoresController');
    Route::resource('CrearCita', 'CitasController');
    Route::resource('keratinas', 'KeratinasController');
    Route::resource('maquillajes', 'MaquillajesController');
    Route::resource('peinados', 'PeinadosController');
    Route::resource('cortes', 'CortesController');
    Route::resource('depilaciones', 'DepilacionesController');
    Route::get('events', 'EventsController@index');
    Route::get('opciones', function () {
        return view('admin.Agenda.agendar');     

    });
    Route::get('servicios', function () {
        return view('admin.servicio.Servicios');
      

    });
});
    /*Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
        Route::resource('login', 'LoginController');
              
    
        });*/
        
   
});



Route::get('/home', 'HomeController@index')->name('home');



Route::get('/home', 'HomeController@index')->name('home');



Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'Auth', 'namespace' => 'Auth'], function () {

   
Route::get('password/reset','ForgotPasswordController@showLinkRequestForm')->name('password.reset');
Route::post('password/email','ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}','ForgotPasswordController@showResetForm')->name('password.reset.token');
Route::post('password/reset','ResetPasswordController@reset');
});
Auth::routes();

resources/views/admin/servicio/cortes_create.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2> <font color="white">Crear servicio de corte</font> </h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <form  method="post" action="{{ route('cortes.store') }}" data-parsley-validate class="form-horizontal form-label-left" >
                      
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre"><p>Nombre <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('nombre') ?: '' }}" id="nombre" name="nombre" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('precio') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="precio"><p>Precio <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('precio') ?: '' }}" id="precio" name="precio" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('precio'))
                                <span class="help-block">{{ $errors->first('precio') }}</span>
                                @endif
                            </div>
                        </div>
                        
                    
                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <button type="submit" class="btn btn-success">Crear Servicio</button>
                                </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/cortes_delete.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                        <h2 > <font color="white">Confirmar borrado del Servicio de color  <strong>{{$corte->nombre}}</strong></font> </h2>
                      <div class="clearfix"></div>
                </div>
                <div class="x_content">
                        <form method="post" action="{{ route('cortes.destroy', ['id' => $corte->id]) }}" data-parsley-validate class="form-horizontal form-label-left">

                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">Si quiero eliminar el servicio  </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/depilaciones_edit.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2> <font color="white"><dt> Editar depilacion:   <strong>{{$depilacion->nombre}}</strong> </dt></font></h2>
                   <div class="clearfix"></div>
                </div>
                <div class="x_content">
                              <br />                 
                                </div>   <form method="post" action="{{ route('depilaciones.update', ['id' => $depilacion->id]) }}" data-parsley-validate class="form-horizontal form-label-left">
                            
        
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre">Nombre <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{$depilacion->nombre}}" id="nombre" name="nombre" class="form-control col-md-7 col-xs-12" >
                                @if ($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group{{ $errors->has('precio') ? ' has-error' : '' }}">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="precio">Precio<span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" value="{{$depilacion->precio}}" id="precio" name="precio" class="form-control col-md-7 col-xs-12">
                                    @if ($errors->has('precio'))
                                    <span class="help-block">{{ $errors->first('precio') }}</span>
                                    @endif
                                </div>
                            </div>


                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <input name="_method" type="hidden" value="PUT">
                                <button type="submit" class="btn btn-success">Guardar Cambios</button>
                                </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/depilaciones_list.blade.php
@extends('layout')

@section('content'  )
<div class="" >

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2><font color="white">Lista de Servicio de Depilacion <a href="{{route('depilaciones.create')}}" class="btn btn-primary btn"><i class="fa fa-plus"></i>Nuevo </a></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content text-center " >
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Precio</th>
                                  <th>Acción</th>
                            
                            </tr>
                        </thead>
                           <tbody>
                            @if (count($depilacion))
                            @foreach($depilacion as $row)
                            <tr>
                                <td>{{$row->nombre}}</td>
                                <td>{{$row->precio}}</td>
                                                              <td>
                                   <a href="{{ route('depilaciones.edit', ['id' => $row->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> Editar </a></i> </a>
                                   <a href="{{ route('depilaciones.show', ['id' => $row->id]) }}" class="btn btn-danger btn-xs"><i class="fa fa-chevron-left"></i> Eliminar </a></i> </a>
                               </td
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/keratinas_delete.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                        <h2 > <font color="white">Confirmar borrado del Servicio de color  <strong>{{$keratina->nombre}}</strong></font> </h2>
                      <div class="clearfix"></div>
                </div>
                <div class="x_content">
                        <form method="post" action="{{ route('keratinas.destroy', ['id' => $keratina->id]) }}" data-parsley-validate class="form-horizontal form-label-left">

                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">Si quiero eliminar el servicio  </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/keratinas_list.blade.php
@extends('layout')

@section('content'  )
<div class="" >

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2><font color="white">Lista de Servicio de Keratina <a href="{{route('keratinas.create')}}" class="btn btn-primary btn"><i class="fa fa-plus"></i>Nuevo </a></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content text-center " >
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Precio</th>
                                  <th>Acción</th>
                            
                            </tr>
                        </thead>
                           <tbody>
                            @if (count($keratina))
                            @foreach($keratina as $row)
                            <tr>
                                <td>{{$row->nombre}}</td>
                                <td>{{$row->precio}}</td>
                                                              <td>
                                   <a href="{{ route('keratinas.edit', ['id' => $row->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> Editar </a></i> </a>
                                   <a href="{{ route('keratinas.show', ['id' => $row->id]) }}" class="btn btn-danger btn-xs"><i class="fa fa-chevron-left"></i> Eliminar </a></i> </a>
                               </td
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/manos_edit.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2> <font color="white"><dt> Editar servicio de Cuidado de Manos:   <strong>{{$mano->nombre}}</strong> </dt></font></h2>
                   <div class="clearfix"></div>
                </div>
                <div class="x_content">
                              <br />                 
                                </div>   <form method="post" action="{{ route('manos.update', ['id' => $mano->id]) }}" data-parsley-validate class="form-horizontal form-label-left">
                            
        
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre">Nombre <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{$mano->nombre}}" id="nombre" name="nombre" class="form-control col-md-7 col-xs-12" >
                                @if ($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group{{ $errors->has('precio') ? ' has-error' : '' }}">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="precio">Precio<span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" value="{{$mano->precio}}" id="precio" name="precio" class="form-control col-md-7 col-xs-12">
                                    @if ($errors->has('precio'))
                                    <span class="help-block">{{ $errors->first('precio') }}</span>
                                    @endif
                                </div>
                            </div>


                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <input name="_method" type="hidden" value="PUT">
                                <button type="submit" class="btn btn-success">Guardar Cambios</button>
                                </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/manos_list.blade.php
@extends('layout')

@section('content'  )
<div class="" >

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2><font color="white">Lista de Servicio Cuidado de Manos <a href="{{route('manos.create')}}" class="btn btn-primary btn"><i class="fa fa-plus"></i>Nuevo </a></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content text-center " >
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Precio</th>
                                  <th>Acción</th>
                            
                            </tr>
                        </thead>
                           <tbody>
                            @if (count($mano))
                            @foreach($mano as $row)
                            <tr>
                                <td>{{$row->nombre}}</td>
                                <td>{{$row->precio}}</td>
                                                              <td>
                                   <a href="{{ route('manos.edit', ['id' => $row->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> Editar </a></i> </a>
                                   <a href="{{ route('manos.show', ['id' => $row->id]) }}" class="btn btn-danger btn-xs"><i class="fa fa-chevron-left"></i> Eliminar </a></i> </a>
                               </td
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/maquillajes_edit.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2> <font color="white"><dt> Editar Maquillaje:   <strong>{{$maquillaje->nombre}}</strong> </dt></font></h2>
                   <div class="clearfix"></div>
                </div>
                <div class="x_content">
                              <br />                 
                                </div>   <form method="post" action="{{ route('maquillajes.update', ['id' => $maquillaje->id]) }}" data-parsley-validate class="form-horizontal form-label-left">
                            
        
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre">Nombre <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{$maquillaje->nombre}}" id="nombre" name="nombre" class="form-control col-md-7 col-xs-12" >
                                @if ($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group{{ $errors->has('precio') ? ' has-error' : '' }}">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="precio">Precio<span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" value="{{$maquillaje->precio}}" id="precio" name="precio" class="form-control col-md-7 col-xs-12">
                                    @if ($errors->has('precio'))
                                    <span class="help-block">{{ $errors->first('precio') }}</span>
                                    @endif
                                </div>
                            </div>


                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <input name="_method" type="hidden" value="PUT">
                                <button type="submit" class="btn btn-success">Guardar Cambios</button>
                                </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/peinados_create.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2> <font color="white">Crear servicio de Peinados</font> </h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br />
                    <form  method="post" action="{{ route('peinados.store') }}" data-parsley-validate class="form-horizontal form-label-left" >
                      
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre"><p>Nombre <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('nombre') ?: '' }}" id="nombre" name="nombre" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('precio') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="precio"><p>Precio <span class="required">*</p></span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{ Request::old('precio') ?: '' }}" id="precio" name="precio" class="form-control col-md-7 col-xs-12">
                                @if ($errors->has('precio'))
                                <span class="help-block">{{ $errors->first('precio') }}</span>
                                @endif
                            </div>
                        </div>
                        
                    
                        <div class="ln_solid"></div>

                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <button type="submit" class="btn btn-success">Crear Servicio</button>
                                </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/peinados_delete.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                        <h2 > <font color="white">Confirmar borrado del Servicio de Peinado <strong>{{$peinado->nombre}}</strong></font> </h2>
                      <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <form method="POST" action="{{ route('peinados.destroy', ['id' =>$peinado->id]) }}">
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">Si quiero eliminar el servicio  </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/peinados_list.blade.php
@extends('layout')

@section('content'  )
<div class="" >

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12 ">
            <div class="x_panel">
                <div class="x_title">
                    <h2><font color="white">Lista de Servicio Peinados <a href="{{route('peinados.create')}}" class="btn btn-primary btn"><i class="fa fa-plus"></i>Nuevo </a></h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content text-center " >
                    <table id="datatable-buttons" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Precio</th>
                                  <th>Acción</th>
                            
                            </tr>
                        </thead>
                           <tbody>
                            @if (count($peinado))
                            @foreach($peinado as $row)
                            <tr>
                                <td>{{$row->nombre}}</td>
                                <td>{{$row->precio}}</td>
                                                              <td>
                                   <a href="{{ route('peinados.edit', ['id' => $row->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-chevron-left"></i> Editar </a></i> </a>
                                   <a href="{{ route('peinados.show', ['id' => $row->id]) }}" class="btn btn-danger btn-xs"><i class="fa fa-chevron-left"></i> Eliminar </a></i> </a>
                               </td
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/servicio/pies_edit.blade.php
@extends('layout')

@section('content')
<div class="">
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2> <font color="white"><dt> Editar Servicio de Cuidado de pies:  <strong>{{$pie->nombre}}</strong></dt></font></h2>
                   <div class="clearfix"></div>
                </div>
                <div class="x_content">
                              <br />                 
                                </div>   <form method="post" action="{{ route('pies.update', ['pie' => $pie->id]) }}" data-parsley-validate class="form-horizontal form-label-left">
                                   
                        <div class="form-group{{ $errors->has('nombre') ? ' has-error' : '' }}">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre">Nombre <span class="required">*</span>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" value="{{$pie->nombre}}" id="nombre" name="nombre" class="form-control col-md-7 col-xs-12" >
                                @if ($errors->has('nombre'))
                                <span class="help-block">{{ $errors->first('nombre') }}</span>
                                @endif
                            </div>
                        </div>

                        
                        <div class="form-group{{ $errors->has('precio') ? ' has-error' : '' }}">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="precio">Precio<span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" value="{{$pie->precio}}" id="precio" name="precio" class="form-control col-md-7 col-xs-12">
                                    @if ($errors->has('precio'))
                                    <span class="help-block">{{ $errors->first('precio') }}</span>
                                    @endif
                                </div>
                            </div>
                                      
                        <div class="ln_solid"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                <input type="hidden" name="_token" value="{{ Session::token() }}">
                                <input name="_method" type="hidden" value="PUT">
                                <button type="submit" class="btn btn-success">Guardar Cambios</button>
                                </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop